### ISSUE TITLE
Error: md5sum missing

### ISSUE THREAD

**Issue by MKLau** [End-to-end-provenance/eep-usecases#5]
After install of RDataTracker from hashtable branch:

!> ddg.run('HT3.R')                                                                                                
 Error in .ddg.record.data(dtype, dname, dpfile, dpfile, dscope, from.env = from.env,  :                           
   could not find function "md5sum"                                                                                
 [1] "Saving ddg.txt in ./HT3_ddg"                                                                                 
 [1] "Saving ddg.json in ./HT3_ddg"                                                                                
 Error in `colnames<-`(`*tmp*`, value = c("FilePath", "DDGPath", "NodePath",  :                                    
   'names' attribute [7] must be the same length as the vector [0]

**Comment by erboose** [comment]
I suspect the NAMESPACE file needs to be updated to import md5sum from devtools when building the package.

**Comment by erboose** [comment]
Sorry, that should be “import from tools”.


From: Boose, Emery
Sent: Friday, June 09, 2017 6:16 PM
To: 'End-to-end-provenance/eep-usecases'; End-to-end-provenance/eep-usecases
Cc: Subscribed
Subject: RE: [End-to-end-provenance/eep-usecases] Error: md5sum missing (#5)

I suspect the NAMESPACE file needs to be updated to import md5sum from devtools when building the package.
